f2fs: sync with stock
* Revert defconfig changes.
* Add f2fs from stock.
* Do changes to fix the following build errors:

../../../../../../kernel/huawei/msm8953/fs/f2fs/dir.c: In function 'f2fs_d_revalidate':
../../../../../../kernel/huawei/msm8953/fs/f2fs/dir.c:933:14: error: 'LOOKUP_CASE_INSENSITIVE' undeclared (first use in this function)
  if (flags & LOOKUP_CASE_INSENSITIVE)
              ^
../../../../../../kernel/huawei/msm8953/fs/f2fs/dir.c:933:14: note: each undeclared identifier is reported only once for each function it appears in
../../../../../../kernel/huawei/msm8953/fs/f2fs/dir.c:937:1: warning: control reaches end of non-void function [-Wreturn-type]
 }

================================

../../../../../../kernel/huawei/msm8953/fs/f2fs/data.c: In function 'f2fs_nat_fiemap':
../../../../../../kernel/huawei/msm8953/fs/f2fs/data.c:967:31: error: 'FIEMAP_MAX_EXTENTS' undeclared (first use in this function)
  if (fiemap.fm_extent_count > FIEMAP_MAX_EXTENTS)
                               ^
../../../../../../kernel/huawei/msm8953/fs/f2fs/data.c:967:31: note: each undeclared identifier is reported only once for each function it appears in
../../../../../../kernel/huawei/msm8953/fs/f2fs/data.c:970:2: error: implicit declaration of function 'fiemap_check_ranges' [-Werror=implicit-function-declaration]
  ret = fiemap_check_ranges(sb, fiemap.fm_start, fiemap.fm_length, &len);
  ^
../../../../../../kernel/huawei/msm8953/fs/f2fs/data.c: In function 'f2fs_write_data_page':
../../../../../../kernel/huawei/msm8953/fs/f2fs/data.c:1393:3: error: implicit declaration of function 'wbc_to_write_cmd' [-Werror=implicit-function-declaration]
   .rw = wbc_to_write_cmd(wbc),

=================================